//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELATORIO_PESAGEM.ModelsBALANCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESAGEM
    {
        public int ID { get; set; }
        public string PLACA { get; set; }
        public string CACAMBA { get; set; }
        public Nullable<int> NUMEROFROTA { get; set; }
        public string MOTORISTA { get; set; }
        public Nullable<int> TRANSPORTADORA { get; set; }
        public Nullable<int> PRODUTO { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public Nullable<long> PESOTOTAL { get; set; }
        public Nullable<long> PESOTARA { get; set; }
        public Nullable<long> PESOLIQUIDO { get; set; }
        public Nullable<System.DateTime> DATAPESAGEM { get; set; }
        public Nullable<long> PESOTOTAL2 { get; set; }
        public Nullable<System.DateTime> DATAPESAGEM2 { get; set; }
        public string STATUS { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERACAO { get; set; }
        public string TIPOPESAGEM { get; set; }
        public Nullable<int> ATIVO { get; set; }
    }
}
