//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELATORIO_PESAGEM.ModelsBALANCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTADORA
    {
        public int ID { get; set; }
        public string NOMETRANS { get; set; }
        public string ENDERECO { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public string CEP { get; set; }
        public string IE { get; set; }
        public string CNPJ { get; set; }
    }
}
