//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELATORIO_PESAGEM.ModelsBALANCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEICULO
    {
        public int ID { get; set; }
        public string PLACA { get; set; }
        public Nullable<int> TRANSPORTADORA { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public Nullable<long> ANO { get; set; }
        public Nullable<long> PESOTARA { get; set; }
        public string UTILIZARTARA { get; set; }
        public Nullable<long> FROTA { get; set; }
        public string CACAMBA { get; set; }
    }
}
